import { readFile, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const inputPath = resolve(root, 'src/assets/audio/night-drive-loop-lullaby-soft-v4.wav');
const outputPath = resolve(root, 'src/assets/audio/night-drive-loop.js');
const inputLabel = relative(root, inputPath).replaceAll('\\', '/');
const wav = await readFile(inputPath);

if (wav.toString('ascii', 0, 4) !== 'RIFF' || wav.toString('ascii', 8, 12) !== 'WAVE') throw new Error('Expected a RIFF/WAVE file.');
let offset = 12;
let format = null;
let pcm = null;
while (offset + 8 <= wav.length) {
  const id = wav.toString('ascii', offset, offset + 4);
  const size = wav.readUInt32LE(offset + 4);
  const start = offset + 8;
  if (id === 'fmt ') format = { type: wav.readUInt16LE(start), channels: wav.readUInt16LE(start + 2), sampleRate: wav.readUInt32LE(start + 4), bits: wav.readUInt16LE(start + 14) };
  if (id === 'data') pcm = wav.subarray(start, start + size);
  offset = start + size + (size & 1);
}
if (!format || !pcm || format.type !== 1 || format.bits !== 16 || format.channels !== 1) throw new Error('Only mono 16-bit PCM WAV input is supported.');

const frames = pcm.length / 2;
const moduleSource = `// Generated by scripts/embed-audio.mjs from ${inputLabel}.\n// The original PCM samples are embedded losslessly; regenerate instead of editing this file by hand.\nexport const sampleRate = ${format.sampleRate};\nexport const pcmBase64 = '${pcm.toString('base64')}';\n`;
await writeFile(outputPath, moduleSource, 'utf8');
console.log(`Embedded ${frames} lossless mono PCM samples at ${format.sampleRate} Hz (${pcm.length} bytes) from ${inputLabel}.`);
